// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqswhtdborijueladlqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxc3dodGRib3JpanVlbGFkbHFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjcyMzYsImV4cCI6MjA2NTkwMzIzNn0.xv5HMgCvkbvu28xop3x9hK4t5i10vXGjASxFwRq0uxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);